version: "3.8"
services:
  jekyll_serve:
    image: ghcr.io/cuthbeorht/davidsciacchettano.ca
    environment:
      - JEKYLL_VERSION=3.8
    command: ['jekyll', 'serve']
    ports:
      - "4000:4000"
  jekyll_dev:
    image: jekyll/jekyll
    environment:
      - JEKYLL_VERSION=3.8
    ports:
      - "4000:4000"
    volumes:
      - ./:/srv/jekyll
    command: ['jekyll', 'serve']