version: "3.8"
services:
  jekyll_serve:
    build:
      context: ./
      dockerfile: localdev.Dockerfile
    environment:
      - JEKYLL_VERSION=3.8
    volumes:
      - ./:/srv/jekyll
    command: ['jekyll', 'serve', "--watch", "--future"]
    ports:
      - "4000:4000"